//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "MTADataModels.h"



@implementation MTAResponse

@synthesize Siri;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAResponse alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    Siri = [[MTASiri alloc] initWithDictionary:[dictionary objectForKey:@"Siri"]];
  }
  return self;
}


@end


@implementation MTAFramedVehicleJourneyRef

@synthesize DataFrameRef;
@synthesize DatedVehicleJourneyRef;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAFramedVehicleJourneyRef alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    DataFrameRef = [dictionary objectForKey:@"DataFrameRef"];
    DatedVehicleJourneyRef = [dictionary objectForKey:@"DatedVehicleJourneyRef"];
  }
  return self;
}


@end


@implementation MTAVehicleLocation

@synthesize Longitude;
@synthesize Latitude;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAVehicleLocation alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    Longitude = [dictionary objectForKey:@"Longitude"];
    Latitude = [dictionary objectForKey:@"Latitude"];
  }
  return self;
}


@end


@implementation MTADistances

@synthesize PresentableDistance;
@synthesize DistanceFromCall;
@synthesize StopsFromCall;
@synthesize CallDistanceAlongRoute;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTADistances alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    PresentableDistance = [dictionary objectForKey:@"PresentableDistance"];
    DistanceFromCall = [dictionary objectForKey:@"DistanceFromCall"];
    StopsFromCall = [dictionary objectForKey:@"StopsFromCall"];
    CallDistanceAlongRoute = [dictionary objectForKey:@"CallDistanceAlongRoute"];
  }
  return self;
}


@end


@implementation MTAExtensions

@synthesize Distances;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAExtensions alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    Distances = [[MTADistances alloc] initWithDictionary:[dictionary objectForKey:@"Distances"]];
  }
  return self;
}


@end


@implementation MTAMonitoredCall

@synthesize Extensions;
@synthesize StopPointRef;
@synthesize VisitNumber;
@synthesize StopPointName;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAMonitoredCall alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    Extensions = [[MTAExtensions alloc] initWithDictionary:[dictionary objectForKey:@"Extensions"]];
    StopPointRef = [dictionary objectForKey:@"StopPointRef"];
    VisitNumber = [dictionary objectForKey:@"VisitNumber"];
    StopPointName = [dictionary objectForKey:@"StopPointName"];
  }
  return self;
}


@end


@implementation MTAOnwardCalls

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAOnwardCalls alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
  }
  return self;
}


@end


@implementation MTAMonitoredVehicleJourney

@synthesize LineRef;
@synthesize DirectionRef;
@synthesize FramedVehicleJourneyRef;
@synthesize JourneyPatternRef;
@synthesize PublishedLineName;
@synthesize OperatorRef;
@synthesize OriginRef;
@synthesize DestinationRef;
@synthesize DestinationName;
@synthesize SituationRef;
@synthesize Monitored;
@synthesize VehicleLocation;
@synthesize Bearing;
@synthesize ProgressRate;
@synthesize BlockRef;
@synthesize VehicleRef;
@synthesize MonitoredCall;
@synthesize OnwardCalls;
@synthesize OriginAimedDepartureTime;
@synthesize ProgressStatus;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAMonitoredVehicleJourney alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    LineRef = [dictionary objectForKey:@"LineRef"];
    DirectionRef = [dictionary objectForKey:@"DirectionRef"];
    
    FramedVehicleJourneyRef = [[MTAFramedVehicleJourneyRef alloc] initWithDictionary:[dictionary objectForKey:@"FramedVehicleJourneyRef"]];
    JourneyPatternRef = [dictionary objectForKey:@"JourneyPatternRef"];
    PublishedLineName = [dictionary objectForKey:@"PublishedLineName"];
    OperatorRef = [dictionary objectForKey:@"OperatorRef"];
    OriginRef = [dictionary objectForKey:@"OriginRef"];
    DestinationRef = [dictionary objectForKey:@"DestinationRef"];
    DestinationName = [dictionary objectForKey:@"DestinationName"];
    
    NSArray* temp =  [dictionary objectForKey:@"SituationRef"];
    SituationRef =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [SituationRef addObject:d];
    }
    Monitored = [dictionary objectForKey:@"Monitored"];
    
    VehicleLocation = [[MTAVehicleLocation alloc] initWithDictionary:[dictionary objectForKey:@"VehicleLocation"]];
    Bearing = [dictionary objectForKey:@"Bearing"];
    ProgressRate = [dictionary objectForKey:@"ProgressRate"];
    BlockRef = [dictionary objectForKey:@"BlockRef"];
    VehicleRef = [dictionary objectForKey:@"VehicleRef"];
    
    MonitoredCall = [[MTAMonitoredCall alloc] initWithDictionary:[dictionary objectForKey:@"MonitoredCall"]];
    
    OnwardCalls = [[MTAOnwardCalls alloc] initWithDictionary:[dictionary objectForKey:@"OnwardCalls"]];
    OriginAimedDepartureTime = [dictionary objectForKey:@"OriginAimedDepartureTime"];
    ProgressStatus = [dictionary objectForKey:@"ProgressStatus"];
  }
  return self;
}


@end


@implementation MTAMonitoredStopVisit

@synthesize MonitoredVehicleJourney;
@synthesize RecordedAtTime;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAMonitoredStopVisit alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    MonitoredVehicleJourney = [[MTAMonitoredVehicleJourney alloc] initWithDictionary:[dictionary objectForKey:@"MonitoredVehicleJourney"]];
    RecordedAtTime = [dictionary objectForKey:@"RecordedAtTime"];
  }
  return self;
}


@end


@implementation MTAStopMonitoringDelivery

@synthesize MonitoredStopVisit;
@synthesize ResponseTimestamp;
@synthesize ValidUntil;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAStopMonitoringDelivery alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    NSArray* temp =  [dictionary objectForKey:@"MonitoredStopVisit"];
    MonitoredStopVisit =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [MonitoredStopVisit addObject:[MTAMonitoredStopVisit objectWithDictionary:d]];
    }
    ResponseTimestamp = [dictionary objectForKey:@"ResponseTimestamp"];
    ValidUntil = [dictionary objectForKey:@"ValidUntil"];
  }
  return self;
}


@end

@implementation MTAVehicleActivity

@synthesize MonitoredVehicleJourney;
@synthesize RecordedAtTime;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAVehicleActivity alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    MonitoredVehicleJourney = [[MTAMonitoredVehicleJourney alloc] initWithDictionary:[dictionary objectForKey:@"MonitoredVehicleJourney"]];
    RecordedAtTime = [dictionary objectForKey:@"RecordedAtTime"];
  }
  return self;
}


@end


@implementation MTAVehicleMonitoringDelivery

@synthesize VehicleActivity;
@synthesize ResponseTimestamp;
@synthesize ValidUntil;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAVehicleMonitoringDelivery alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    NSArray* temp =  [dictionary objectForKey:@"VehicleActivity"];
    VehicleActivity =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [VehicleActivity addObject:[MTAVehicleActivity objectWithDictionary:d]];
    }
    ResponseTimestamp = [dictionary objectForKey:@"ResponseTimestamp"];
    ValidUntil = [dictionary objectForKey:@"ValidUntil"];
  }
  return self;
}


@end


@implementation MTAServiceDelivery

@synthesize ResponseTimestamp;
@synthesize StopMonitoringDelivery;
@synthesize VehicleMonitoringDelivery;
@synthesize SituationExchangeDelivery;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTAServiceDelivery alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    ResponseTimestamp = [dictionary objectForKey:@"ResponseTimestamp"];
    
    NSArray* temp =  [dictionary objectForKey:@"StopMonitoringDelivery"];
    StopMonitoringDelivery =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [StopMonitoringDelivery addObject:[MTAStopMonitoringDelivery objectWithDictionary:d]];
    }
    
    temp =  [dictionary objectForKey:@"VehicleMonitoringDelivery"];
    VehicleMonitoringDelivery =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [VehicleMonitoringDelivery addObject:[MTAVehicleMonitoringDelivery objectWithDictionary:d]];
    }
    
    temp =  [dictionary objectForKey:@"SituationExchangeDelivery"];
    SituationExchangeDelivery =  [[NSMutableArray alloc] init];
    for (NSDictionary *d in temp) {
      [SituationExchangeDelivery addObject:d];
    }
  }
  return self;
}


@end


@implementation MTASiri

@synthesize ServiceDelivery;

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
  id obj = [[MTASiri alloc] initWithDictionary:dictionary];
  return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
  self=[super init];
  if(self)
  {
    
    ServiceDelivery = [[MTAServiceDelivery alloc] initWithDictionary:[dictionary objectForKey:@"ServiceDelivery"]];
  }
  return self;
}


@end

//JsonModel.m End
