//
// JsonModel.h
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
// To use this code you need to download and reference JSONKit
// https://github.com/johnezang/JSONKit
//

#import <Foundation/Foundation.h>

@class OBAAgency;
@class OBARoute;
@class OBAStop;
//@class OBAAgency2;
//@class OBARoute2;
@class OBAName;
@class OBAPolyline;
@class OBAStopGroup;
@class OBAStopGrouping;
//@class OBAPolyline2;
@class OBAData;

@interface OBAResponse : NSObject
{
  NSNumber * CurrentTime;
  NSString * Text;
  OBAData * Data;
  NSNumber * Code;
  NSNumber * Version;
}

@property(nonatomic,retain) NSNumber * CurrentTime;
@property(nonatomic,retain) NSString * Text;
@property(nonatomic,retain) OBAData * Data;
@property(nonatomic,retain) NSNumber * Code;
@property(nonatomic,retain) NSNumber * Version;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBAAgency : NSObject
{
  NSString * Id;
  NSString * PrivateService;
  NSString * Phone;
  NSString * Timezone;
  NSString * Disclaimer;
  NSString * Name;
  NSString * Lang;
  NSString * Url;
}

@property(nonatomic,retain) NSString * Id;
@property(nonatomic,retain) NSString * PrivateService;
@property(nonatomic,retain) NSString * Phone;
@property(nonatomic,retain) NSString * Timezone;
@property(nonatomic,retain) NSString * Disclaimer;
@property(nonatomic,retain) NSString * Name;
@property(nonatomic,retain) NSString * Lang;
@property(nonatomic,retain) NSString * Url;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBARoute : NSObject
{
  NSString * Id;
  NSString * TextColor;
  NSString * Color;
  NSString * Description;
  NSString * LongName;
  OBAAgency * Agency;
  NSString * ShortName;
  NSNumber * Type;
  NSString * Url;
}

@property(nonatomic,retain) NSString * Id;
@property(nonatomic,retain) NSString * TextColor;
@property(nonatomic,retain) NSString * Color;
@property(nonatomic,retain) NSString * Description;
@property(nonatomic,retain) NSString * LongName;
@property(nonatomic,retain) OBAAgency * Agency;
@property(nonatomic,retain) NSString * ShortName;
@property(nonatomic,retain) NSNumber * Type;
@property(nonatomic,retain) NSString * Url;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBAStop : NSObject
{
  NSString * Id;
  NSNumber * Lon;
  NSMutableArray * Routes;
  NSString * Direction;
  NSNumber * LocationType;
  NSString * Name;
  NSString * WheelchairBoarding;
  NSString * Code;
  NSNumber * Lat;
}

@property(nonatomic,retain) NSString * Id;
@property(nonatomic,retain) NSNumber * Lon;
@property(nonatomic,retain) NSMutableArray * Routes;
@property(nonatomic,retain) NSString * Direction;
@property(nonatomic,retain) NSNumber * LocationType;
@property(nonatomic,retain) NSString * Name;
@property(nonatomic,retain) NSString * WheelchairBoarding;
@property(nonatomic,retain) NSString * Code;
@property(nonatomic,retain) NSNumber * Lat;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end
//
//
//@interface OBAAgency2 : NSObject
//{
//  NSString * PrivateService;
//  NSString * Id;
//  NSString * Timezone;
//  NSString * Phone;
//  NSString * Disclaimer;
//  NSString * Name;
//  NSString * Lang;
//  NSString * Url;
//}
//
//@property(nonatomic,retain) NSString * PrivateService;
//@property(nonatomic,retain) NSString * Id;
//@property(nonatomic,retain) NSString * Timezone;
//@property(nonatomic,retain) NSString * Phone;
//@property(nonatomic,retain) NSString * Disclaimer;
//@property(nonatomic,retain) NSString * Name;
//@property(nonatomic,retain) NSString * Lang;
//@property(nonatomic,retain) NSString * Url;
//
//+ (id) objectWithDictionary:(NSDictionary*)dictionary;
//- (id) initWithDictionary:(NSDictionary*)dictionary;
//
//@end
//
//
//@interface OBARoute2 : NSObject
//{
//  NSString * Id;
//  NSString * TextColor;
//  NSString * Color;
//  NSString * Description;
//  NSString * LongName;
//  OBAAgency2 * Agency;
//  NSNumber * Type;
//  NSString * ShortName;
//  NSString * Url;
//}
//
//@property(nonatomic,retain) NSString * Id;
//@property(nonatomic,retain) NSString * TextColor;
//@property(nonatomic,retain) NSString * Color;
//@property(nonatomic,retain) NSString * Description;
//@property(nonatomic,retain) NSString * LongName;
//@property(nonatomic,retain) OBAAgency2 * Agency;
//@property(nonatomic,retain) NSNumber * Type;
//@property(nonatomic,retain) NSString * ShortName;
//@property(nonatomic,retain) NSString * Url;
//
//+ (id) objectWithDictionary:(NSDictionary*)dictionary;
//- (id) initWithDictionary:(NSDictionary*)dictionary;
//
//@end
//

@interface OBAName : NSObject
{
  NSMutableArray * Names;
  NSString * Name;
  NSString * Type;
}

@property(nonatomic,retain) NSMutableArray * Names;
@property(nonatomic,retain) NSString * Name;
@property(nonatomic,retain) NSString * Type;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBAPolyline : NSObject
{
  NSString * Levels;
  NSNumber * Length;
  NSString * Points;
}

@property(nonatomic,retain) NSString * Levels;
@property(nonatomic,retain) NSNumber * Length;
@property(nonatomic,retain) NSString * Points;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBAStopGroup : NSObject
{
  NSString * Id;
  OBAName * Name;
  NSMutableArray * SubGroups;
  NSMutableArray * StopIds;
  NSMutableArray * Polylines;
}

@property(nonatomic,retain) NSString * Id;
@property(nonatomic,retain) OBAName * Name;
@property(nonatomic,retain) NSMutableArray * SubGroups;
@property(nonatomic,retain) NSMutableArray * StopIds;
@property(nonatomic,retain) NSMutableArray * Polylines;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end


@interface OBAStopGrouping : NSObject
{
  NSString * Ordered;
  NSMutableArray * StopGroups;
  NSString * Type;
}

@property(nonatomic,retain) NSString * Ordered;
@property(nonatomic,retain) NSMutableArray * StopGroups;
@property(nonatomic,retain) NSString * Type;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end

////
//@interface OBAPolyline2 : NSObject
//{
//  NSString * Levels;
//  NSNumber * Length;
//  NSString * Points;
//}
//
//@property(nonatomic,retain) NSString * Levels;
//@property(nonatomic,retain) NSNumber * Length;
//@property(nonatomic,retain) NSString * Points;
//
//+ (id) objectWithDictionary:(NSDictionary*)dictionary;
//- (id) initWithDictionary:(NSDictionary*)dictionary;
//
//@end
//

@interface OBAData : NSObject
{
  NSMutableArray * Stops;
  OBARoute * Route;
  NSMutableArray * StopGroupings;
  NSMutableArray * Polylines;
}

@property(nonatomic,retain) NSMutableArray * Stops;
@property(nonatomic,retain) OBARoute * Route;
@property(nonatomic,retain) NSMutableArray * StopGroupings;
@property(nonatomic,retain) NSMutableArray * Polylines;

+ (id) objectWithDictionary:(NSDictionary*)dictionary;
- (id) initWithDictionary:(NSDictionary*)dictionary;

@end

//JsonModel.h End

